# texel-art-website/docker-compose.yml
version: "3.9"
services:
  api:
    build: .
    environment:
      ADDON_MODULE: BlendArMocap
      MOCAP_SCRIPT: /root/.config/blender/4.1/scripts/addons/BlendArMocap/src/addon_script.py
      TRANSFORM_SCRIPT: /root/.config/blender/4.1/scripts/addons/BlendArMocap/src/transform_addon_script.py
      UPLOAD_DIR: /shared/in
      OUTPUT_DIR: /shared/out
      HEADLESS: "1"
      RIG_BLEND_PATH: /shared/rigs/LetsTryThisOne3.blend
    volumes:
      - ./shared:/shared
      - ./shared/rigs/LetsTryThisOne3.blend:/shared/rigs/LetsTryThisOne3.blend:ro

    ports:
      - "8000:8000"
    # If your API calls Blender via subprocess, no extra service is needed.
    # Ensure subprocess uses: xvfb-run -s "-screen 0 1920x1080x24" blender --factory-startup --addons $ADDON_MODULE --python $BLENDER_ADDON_SCRIPT -- ...
