# texel-art-website/docker-compose.yml
version: "3.9"
services:
  api:
    build: .
    environment:
      ADDON_MODULE: ${ADDON_MODULE:-BlendArMocap}
      BLENDER_ADDON_SCRIPT: ${BLENDER_ADDON_SCRIPT:-/opt/addons/BlendArMocap/addon_script.py}
      BLENDER_TRANSFORM_SCRIPT: ${BLENDER_TRANSFORM_SCRIPT:-/opt/addons/BlendArMocap/transform_addon_script.py}
      UPLOAD_DIR: ${UPLOAD_DIR:-/shared/in}
      OUTPUT_DIR: ${OUTPUT_DIR:-/shared/out}
      HEADLESS: "1"
    volumes:
      - ./shared:/shared
    ports:
      - "8000:8000"
    # If your API calls Blender via subprocess, no extra service is needed.
    # Ensure subprocess uses: xvfb-run -s "-screen 0 1920x1080x24" blender --factory-startup --addons $ADDON_MODULE --python $BLENDER_ADDON_SCRIPT -- ...
